apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-ssm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::494970943538:role/eks-ssm-ps-dev-role

---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  annotations:
spec:
  serviceAccountName: oidc-ssm
  containers:
    - name: demo
      image: 494970943538.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-store
      imagePullPolicy: Always
      env:
        - name: PARAMS
          value: "dev.payment.cart_port dev.payment.user_port dev.payment.cart_host"
---

